stages:
- build
- deploy

build:
  image: alpine:3.9
  stage: build
  script:
  - apk add --no-cache make python3
  - pip3 install sphinx==2.2.1 sphinx-rtd-theme==0.4.3 sphinxcontrib-httpdomain docutils==0.16
  - export REPO_NAME=eaasi_user_handbook
  artifacts:
    paths:
    - build

pages:
  variables:
    GIT_STRATEGY: none
  image: busybox
  stage: deploy
  dependencies:
  - build
  script:
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - main
